# Generated by Django 4.2.5 on 2023-11-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprofile', '0002_alter_escortavailability_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escortprofiletag',
            name='escort_profile',
            field=models.ManyToManyField(to='eprofile.escortprofile'),
        ),
    ]
