# Generated by Django 4.2.5 on 2023-11-04 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_tag_id_alter_tag_name'),
        ('eprofile', '0003_alter_escortprofiletag_escort_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='escortprofile',
            name='tags',
            field=models.ManyToManyField(through='eprofile.EscortProfileTag', to='tag.tag'),
        ),
        migrations.RemoveField(
            model_name='escortprofiletag',
            name='escort_profile',
        ),
        migrations.AddField(
            model_name='escortprofiletag',
            name='escort_profile',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='eprofile.escortprofile'),
            preserve_default=False,
        ),
    ]
