# Generated by Django 4.2.5 on 2023-10-03 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit_purchase', 'Purchase of Credits'), ('profile_highlight', 'Profile Highlight'), ('booking', 'Booking'), ('booking_cancellation', 'Booking Cancellation'), ('booking_completion', 'Booking Completion'), ('booking_reschedule', 'Booking Reschedule'), ('booking_reschedule_cancellation', 'Booking Reschedule Cancellation'), ('booking_reschedule_completion', 'Booking Reschedule Completion')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], max_length=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('payment_gateway_response', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
